// https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values
export enum EKey {
  Right = 'KeyD',
  Left = 'KeyA',
  Up = 'KeyW',
  Down = 'KeyS',
  E = 'KeyE',
  R = 'KeyR',
  F = 'KeyF',
  F1 = 'F1',
  Digit1 = 'Digit1',
  Digit2 = 'Digit2',
  Digit3 = 'Digit3',
  Digit4 = 'Digit4',
  Digit5 = 'Digit5',
  Digit6 = 'Digit6',
  Digit7 = 'Digit7',
  Digit8 = 'Digit8',
  Digit9 = 'Digit9',
}

export enum EFormatKey {
  KeyD = 'D',
  KeyA = 'A',
  KeyW = 'W',
  KeyS = 'S',
  KeyE = 'E',
  KeyR = 'R',
  KeyF = 'F',
  F1 = 'F1',
  Digit1 = '1',
  Digit2 = '2',
  Digit3 = '3',
  Digit4 = '4',
  Digit5 = '5',
  Digit6 = '6',
  Digit7 = '7',
  Digit8 = '8',
  Digit9 = '9',
}
